### ISSUE TITLE
xSPUsageApplication not manage provision issue with service application proxy

### ISSUE THREAD

**Issue by luigilink** [PowerShell/xSharePoint#247] opened 2016-03-29 15:40 UTC
It's a known issue with the provision of Usage Service Application, to fix this issue add the following code in the DSCRessource MSFT_xSPUsageApplication :

$spUsageApplicationProxy= Get-SPServiceApplicationProxy | Where-Object -Property TypeName -eq "**Usage and Health Data Collection Proxy**"

if($spUsageApplicationProxy.Status -eq "**Disabled**")
{$spUsageApplicationProxy.**Provision**()}

Thanks in advance.
If you need help, do not hesitate to ping me ;)

**Comment by BrianFarnhill** [comment] 2016-03-30 02:08
@luigilink Thanks for reporting this - can you give me a little more info? What's the specific error you are seeing when this runs? I'm just after a little more detail because the get method where that script comes from shouldn't make changes to the system, and the Provision method would do this. I'm happy to look at how we put this in to the set method and trigger it from there, but I just want to understand the root cause first.

**Comment by andy-cox** [comment] 2016-03-30 07:31
I think this may be related to [this issue](https://tristanwatkins.com/fixing-the-usage-and-health-data-collection-sa/) where the Usage and Health Collection Proxy does not start? I've experienced this a few times.

**Comment by luigilink** [comment] 2016-03-30 07:48
Yes @andy-cox this is the right issue. When the Usage Service Application is provisioned, the associated proxy always stays in **stopped** status in "Manage Service Application".

**Comment by BrianFarnhill** [comment] 2016-04-01 04:44
Hey guys, I have a fix for this in #254 - it will also detect where the proxy isn't running in an existing deployment and turn it on, so it should self heal any environment impacted by this issue already. I'll close this issue off when it gets merged to dev

**Comment by BrianFarnhill** [comment] 2016-04-04 23:01
This fix has now been merged in to dev - if you grab the latest dev build and run it on an existing environment with the issue it should resolve itself. Closing this one off

**Closed by BrianFarnhill** 2016-04-04 23:01 UTC
Labels: bug, need review
