### ISSUE TITLE
Prerequisite Installer Does Not Validate File Paths

### ISSUE THREAD

**Issue by HiltonGiesenow** [PowerShell/xSharePoint#100] opened 2015-11-25 14:38 UTC
If you set the Prere installer to use Offline mode, and supply it with paths to the prereqs, it doesn't validate that they are actually available at the path supplied, and the installer gets stuck in an endless reboot loop.

**Comment by NikCharlebois** [comment] 2015-11-25 14:40
Thanks Hilton, actually, on Windows Server 2012 R2, even if the Prereq mode is set to online, I get stuck in an infinite loop. I will take a closer look at the event logs to see if I can figure out what the issue is.

**Comment by BrianFarnhill** [comment] 2015-11-25 21:43
So there was one issue we found with the parameters not being formatted correctly, the fix for which is in my current PR #97 along with a couple of other things, so that might be the cause of what you are looking for (the discussion on this is in issue number #88).

There is a larger issue here about the way things get caught in reboots here and us essentially relying on the prerequisite installer and how it behaves to meet our needs. I think ultimately we need to rewrite this resource to manually install the required prerequisites rather than calling the prerequisite installer. This will give us more control over the process and let us do more than run and exe and hope for the right exit code. What do you guys think?

**Comment by HiltonGiesenow** [comment] 2015-11-26 04:45
hmm, I'm a bit in two minds. On the one hand it would be much better to
have more control, but on the other we're reinventing the wheel. Perhaps
there's just a better way to get output from the prereq.exe. For instance,
when it failed for me, the gui showed up and gave me a link to the error
log - perhaps there's a way to check for an error log more explicitly? On
the other hand, that also would be ugly and we'd probably end up parsing
the log for the real error.

Perhaps it boils down to if we can reasonably and feasibly (time-wise)
rebuild this functionality and keep it up to date if/when it ever changes?
Ironically, what's the prereq installer is doing is pretty much what DSC
was designed to do - install windows features and msi's :-). If we really
wanted to, we could even look to download the installs to a known location
so that future (re)installs could naturally become offline installs - what
do you think? We should just do so in an idempotent way, like
"keepdownloads = $true" or something like that


-- Hilton
__________________________
Hilton Giesenow

(w) http://hilton.giesenow.com/
(m) +27 (0)83 642 6208

**Comment by BrianFarnhill** [comment] 2015-11-27 11:00
I'm closing this one now as the original issue about the prereq installer not validating the file paths was merged in through PR #101 - but I've also opened a new issue to discuss the approach of the prereq installer separately at #102

**Closed by BrianFarnhill** 2015-11-27 11:00 UTC
