### ISSUE TITLE
Session is Broken

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/xSharePoint#51] opened 2015-07-09 18:19 UTC
Hi guys, the problem is most likely on my end, but using the singlefarm example you provided, I keep getting the following error:

This event indicates that a non-terminating error was thrown when DSCEngine was executing Set-TargetResource on MSFT_xSPCreateFarm DSC resource. FullyQualifiedErrorId is InvalidSessionState,localhost. Error Message is Cannot invoke the pipeline because the runspace is not in the Opened state. Current state of the runspace is 'Broken'..

The server reboots twice for the Prerequisites installation, then installed the SP bits without any issues. It is when I hit the xSPCreateFarm that things start going wrong. I suspect the xSPClearRemoteSession is the culprit. Here is my config (still the default):

xSPClearRemoteSessions ClearRemotePowerShellSessions
        {
            ClearRemoteSessions = $true
        }

Any ideas/pointers as to what I may be doing wrong? Thanks

Nik

**Comment by BrianFarnhill** [comment] 2015-07-09 22:26
The clear remote sessions object is just used to ensure no existing remote sessions are interfering with the script. The error you are getting is insite of your xSPCreateFarm object, so it is nothing to do with the remote sessions one. Can you post your config file in full for me to look at?

**Comment by NikCharlebois** [comment] 2015-07-09 22:32
Thanks Brian, here it is

Configuration SharePointServer
{
    param (
        [Parameter(Mandatory=$true)] [ValidateNotNullorEmpty()] 
        [PSCredential] $FarmAccount,

        [Parameter(Mandatory=$true)]
        [String[]] $NodeGUID
    )

    Import-DscResource -ModuleName xSharePoint
    Import-DscResource -ModuleName xWebAdministration
    Import-DscResource -ModuleName xCredSSP
    Import-DscResource -ModuleName xDisk

    node $NodeGUID
    {
        xCredSSP CredSSPServer { Ensure = "Present"; Role = "Server" } 
        xCredSSP CredSSPClient { Ensure = "Present"; Role = "Client"; DelegateComputers = "DSCPull" }
        File SPBinaryDownload
        {
            DestinationPath = "C:\SPInstall"
            Ensure          = "Present"
            SourcePath      = "\\DSCPULL\PullServer\SharePoint 2013\SPInstall"
            Type            = "Directory"
            Recurse         = $true
        }
        File UlsViewerDownload
        {
            DestinationPath = "C:\Tools\UlsViewer.exe"
            Ensure          = "Present"
            SourcePath      = "\\DSCPull\PullServer\ULSViewer\ULSViewer.exe"
            Type            = "File"
        }

        #**********************************************************
        # Binary installation
        #
        # This section triggers installation of both SharePoint
        # as well as the prerequisites required
        #********************************************************** 
        xSPClearRemoteSessions ClearRemotePowerShellSessions
        {
            ClearRemoteSessions = $false
        }
        xSPInstallPrereqs InstallPrerequisites
        {
            InstallerPath     = "C:\SPInstall\Prerequisiteinstaller.exe"
            OnlineMode        = $false
            SQLNCli           = "C:\SPInstall\prerequisiteinstallerfiles\sqlncli.msi"
            NETFX             = "C:\SPInstall\prerequisiteinstallerfiles\dotNetFx45_Full_setup.exe"
            IDFX              = "C:\SPInstall\prerequisiteinstallerfiles\Windows6.1-KB974405-x64.msu"
            Sync              = "C:\SPInstall\prerequisiteinstallerfiles\Synchronization.msi"
            AppFabric         = "C:\SPInstall\prerequisiteinstallerfiles\WindowsServerAppFabricSetup_x64.exe"
            IDFX11            = "C:\SPInstall\prerequisiteinstallerfiles\MicrosoftIdentityExtensions-64.msi"
            MSIPCClient       = "C:\SPInstall\prerequisiteinstallerfiles\setup_msipc_x64.msi"
            WCFDataServices   = "C:\SPInstall\prerequisiteinstallerfiles\WcfDataServices.exe"
            KB2671763         = "C:\SPInstall\prerequisiteinstallerfiles\AppFabric1.1-RTM-KB2671763-x64-ENU.exe"
            WCFDataServices56 = "C:\SPInstall\prerequisiteinstallerfiles\WcfDataServices56.exe"
            PowerShell        = "C:\SPInstall\prerequisiteinstallerfiles\Windows6.1-KB2506143-x64.msu"
            DependsOn         = "[xSPClearRemoteSessions]ClearRemotePowerShellSessions"
        }
        xSPInstall InstallBinaries
        {
            BinaryDir  = "C:\SPInstall"
            ProductKey = "N3MDM-DXR3H-JD7QH-QKKCR-BY2Y7"
            DependsOn  = "[xSPInstallPrereqs]InstallPrerequisites"
        }

        #**********************************************************
        # IIS clean up
        #
        # This section removes all default sites and application
        # pools from IIS as they are not required
        #**********************************************************

        xWebAppPool RemoveDotNet2Pool         { Name = ".NET v2.0";            Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites" }
        xWebAppPool RemoveDotNet2ClassicPool  { Name = ".NET v2.0 Classic";    Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites" }
        xWebAppPool RemoveDotNet45Pool        { Name = ".NET v4.5";            Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites"; }
        xWebAppPool RemoveDotNet45ClassicPool { Name = ".NET v4.5 Classic";    Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites"; }
        xWebAppPool RemoveClassicDotNetPool   { Name = "Classic .NET AppPool"; Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites" }
        xWebAppPool RemoveDefaultAppPool      { Name = "DefaultAppPool";       Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites" }
        xWebSite    RemoveDefaultWebSite      { Name = "Default Web Site";     Ensure = "Absent"; PhysicalPath = "C:\inetpub\wwwroot"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites" }
        

        #**********************************************************
        # Basic farm configuration
        #
        # This section creates the new SharePoint farm object, and
        # provisions generic services and components used by the
        # whole farm
        #**********************************************************

        xSPCreateFarm CreateSPFarm
        {
            DatabaseServer           = "sp2013-dsc.contoso.com"
            FarmConfigDatabaseName   = "SP_Config"
            Passphrase               = "pass@word1"
            FarmAccount              = $FarmAccount
            InstallAccount           = $FarmAccount
            AdminContentDatabaseName = "SP_AdminContent"
            DependsOn                = "[xSPInstall]InstallBinaries"
        }
        
        xSPStateServiceApp StateServiceApp
        {
            Name           = "State Service Application"
            DatabaseName   = "SP_State"
            InstallAccount = $FarmAccount
            DependsOn      = "[xSPCreateFarm]CreateSPFarm"
        }
        
        xSPWebApplication HostNameSiteCollectionWebApp
        {
            Name                   = "SharePoint Sites"
            ApplicationPool        = "SharePoint Sites"
            ApplicationPoolAccount = $FarmAccount.UserName
            AllowAnonymous         = $false
            AuthenticationMethod   = "NTLM"
            DatabaseName           = "SP_Content_01"
            DatabaseServer         = "sp2013-dsc.contoso.com"
            Url                    = "http://localhost"
            Port                   = 80
            InstallAccount         = $FarmAccount
        }

        xSPServiceAppPool MainServiceAppPool
        {
            Name           = "SharePoint Service Applications"
            ServiceAccount = $FarmAccount.UserName
            InstallAccount = $FarmAccount
            DependsOn      = "[xSPCreateFarm]CreateSPFarm"
        }
       
        LocalConfigurationManager
        {
            RebootNodeIfNeeded = $true
        }
    }
}
$Computers = @("SP2013-DSC")

write-host "Generating GUIDs and creating MOF files..."
foreach ($Node in $Computers)
{
    $NewGUID = [guid]::NewGuid()
    $NewLine = "{0},{1}" -f $Node,$NewGUID

    $ConfigData = @{
    AllNodes = @(
        @{
            NodeName                    = "$NewGUID"
            PSDscAllowPlainTextPassword = $true
        }
        )
    }

    SharePointServer -ConfigurationData $ConfigData -OutputPath ".\TestConfig" -NodeGUID $NewGUID
    $NewLine | add-content -path "$env:SystemDrive\Program Files\WindowsPowershell\DscService\Configuration\dscnodes.csv"
    
}
write-host "Creating checksums..."
New-DSCCheckSum -ConfigurationPath .\TestConfig -OutPath .\TestConfig -Verbose -Force

write-host "Copying configurations to pull service configuration store..."
$SourceFiles = (Get-Location -PSProvider FileSystem).Path + "\TestConfig\*.mof*"
$TargetFiles = "$env:SystemDrive\Program Files\WindowsPowershell\DscService\Configuration"
Move-Item $SourceFiles $TargetFiles -Force
Remove-Item ((Get-Location -PSProvider FileSystem).Path + "\TestConfig\")

**Comment by NikCharlebois** [comment] 2015-07-09 22:33
Thanks Brian, here it is :
Configuration SharePointServer
{
    param (
        [Parameter(Mandatory=$true)] [ValidateNotNullorEmpty()] 
        [PSCredential] $FarmAccount,

        [Parameter(Mandatory=$true)]
        [String[]] $NodeGUID
    )

    Import-DscResource -ModuleName xSharePoint
    Import-DscResource -ModuleName xWebAdministration
    Import-DscResource -ModuleName xCredSSP
    Import-DscResource -ModuleName xDisk

    node $NodeGUID
    {
        xCredSSP CredSSPServer { Ensure = "Present"; Role = "Server" } 
        xCredSSP CredSSPClient { Ensure = "Present"; Role = "Client"; DelegateComputers = "DSCPull" }
        File SPBinaryDownload
        {
            DestinationPath = "C:\SPInstall"
            Ensure          = "Present"
            SourcePath      = "\\DSCPULL\PullServer\SharePoint 2013\SPInstall"
            Type            = "Directory"
            Recurse         = $true
        }
        File UlsViewerDownload
        {
            DestinationPath = "C:\Tools\UlsViewer.exe"
            Ensure          = "Present"
            SourcePath      = "\\DSCPull\PullServer\ULSViewer\ULSViewer.exe"
            Type            = "File"
        }

        #**********************************************************
        # Binary installation
        #
        # This section triggers installation of both SharePoint
        # as well as the prerequisites required
        #********************************************************** 
        xSPClearRemoteSessions ClearRemotePowerShellSessions
        {
            ClearRemoteSessions = $false
        }
        xSPInstallPrereqs InstallPrerequisites
        {
            InstallerPath     = "C:\SPInstall\Prerequisiteinstaller.exe"
            OnlineMode        = $false
            SQLNCli           = "C:\SPInstall\prerequisiteinstallerfiles\sqlncli.msi"
            NETFX             = "C:\SPInstall\prerequisiteinstallerfiles\dotNetFx45_Full_setup.exe"
            IDFX              = "C:\SPInstall\prerequisiteinstallerfiles\Windows6.1-KB974405-x64.msu"
            Sync              = "C:\SPInstall\prerequisiteinstallerfiles\Synchronization.msi"
            AppFabric         = "C:\SPInstall\prerequisiteinstallerfiles\WindowsServerAppFabricSetup_x64.exe"
            IDFX11            = "C:\SPInstall\prerequisiteinstallerfiles\MicrosoftIdentityExtensions-64.msi"
            MSIPCClient       = "C:\SPInstall\prerequisiteinstallerfiles\setup_msipc_x64.msi"
            WCFDataServices   = "C:\SPInstall\prerequisiteinstallerfiles\WcfDataServices.exe"
            KB2671763         = "C:\SPInstall\prerequisiteinstallerfiles\AppFabric1.1-RTM-KB2671763-x64-ENU.exe"
            WCFDataServices56 = "C:\SPInstall\prerequisiteinstallerfiles\WcfDataServices56.exe"
            PowerShell        = "C:\SPInstall\prerequisiteinstallerfiles\Windows6.1-KB2506143-x64.msu"
            DependsOn         = "[xSPClearRemoteSessions]ClearRemotePowerShellSessions"
        }
        xSPInstall InstallBinaries
        {
            BinaryDir  = "C:\SPInstall"
            ProductKey = "xxxxxxxxxxxx"
            DependsOn  = "[xSPInstallPrereqs]InstallPrerequisites"
        }

        #**********************************************************
        # IIS clean up
        #
        # This section removes all default sites and application
        # pools from IIS as they are not required
        #**********************************************************

        xWebAppPool RemoveDotNet2Pool         { Name = ".NET v2.0";            Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites" }
        xWebAppPool RemoveDotNet2ClassicPool  { Name = ".NET v2.0 Classic";    Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites" }
        xWebAppPool RemoveDotNet45Pool        { Name = ".NET v4.5";            Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites"; }
        xWebAppPool RemoveDotNet45ClassicPool { Name = ".NET v4.5 Classic";    Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites"; }
        xWebAppPool RemoveClassicDotNetPool   { Name = "Classic .NET AppPool"; Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites" }
        xWebAppPool RemoveDefaultAppPool      { Name = "DefaultAppPool";       Ensure = "Absent"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites" }
        xWebSite    RemoveDefaultWebSite      { Name = "Default Web Site";     Ensure = "Absent"; PhysicalPath = "C:\inetpub\wwwroot"; DependsOn = "[xSPInstallPrereqs]InstallPrerequisites" }
        

        #**********************************************************
        # Basic farm configuration
        #
        # This section creates the new SharePoint farm object, and
        # provisions generic services and components used by the
        # whole farm
        #**********************************************************

        xSPCreateFarm CreateSPFarm
        {
            DatabaseServer           = "sp2013-dsc.contoso.com"
            FarmConfigDatabaseName   = "SP_Config"
            Passphrase               = "pass@word1"
            FarmAccount              = $FarmAccount
            InstallAccount           = $FarmAccount
            AdminContentDatabaseName = "SP_AdminContent"
            DependsOn                = "[xSPInstall]InstallBinaries"
        }
        
        xSPStateServiceApp StateServiceApp
        {
            Name           = "State Service Application"
            DatabaseName   = "SP_State"
            InstallAccount = $FarmAccount
            DependsOn      = "[xSPCreateFarm]CreateSPFarm"
        }
        
        xSPWebApplication HostNameSiteCollectionWebApp
        {
            Name                   = "SharePoint Sites"
            ApplicationPool        = "SharePoint Sites"
            ApplicationPoolAccount = $FarmAccount.UserName
            AllowAnonymous         = $false
            AuthenticationMethod   = "NTLM"
            DatabaseName           = "SP_Content_01"
            DatabaseServer         = "sp2013-dsc.contoso.com"
            Url                    = "http://localhost"
            Port                   = 80
            InstallAccount         = $FarmAccount
        }

        xSPServiceAppPool MainServiceAppPool
        {
            Name           = "SharePoint Service Applications"
            ServiceAccount = $FarmAccount.UserName
            InstallAccount = $FarmAccount
            DependsOn      = "[xSPCreateFarm]CreateSPFarm"
        }
       
        LocalConfigurationManager
        {
            RebootNodeIfNeeded = $true
        }
    }
}
$Computers = @("SP2013-DSC")

write-host "Generating GUIDs and creating MOF files..."
foreach ($Node in $Computers)
{
    $NewGUID = [guid]::NewGuid()
    $NewLine = "{0},{1}" -f $Node,$NewGUID

    $ConfigData = @{
    AllNodes = @(
        @{
            NodeName                    = "$NewGUID"
            PSDscAllowPlainTextPassword = $true
        }
        )
    }

    SharePointServer -ConfigurationData $ConfigData -OutputPath ".\TestConfig" -NodeGUID $NewGUID
    $NewLine | add-content -path "$env:SystemDrive\Program Files\WindowsPowershell\DscService\Configuration\dscnodes.csv"
    
}
write-host "Creating checksums..."
New-DSCCheckSum -ConfigurationPath .\TestConfig -OutPath .\TestConfig -Verbose -Force

write-host "Copying configurations to pull service configuration store..."
$SourceFiles = (Get-Location -PSProvider FileSystem).Path + "\TestConfig\*.mof*"
$TargetFiles = "$env:SystemDrive\Program Files\WindowsPowershell\DscService\Configuration"
Move-Item $SourceFiles $TargetFiles -Force
Remove-Item ((Get-Location -PSProvider FileSystem).Path + "\TestConfig\")

**Comment by NikCharlebois** [comment] 2015-07-09 23:52
I should have mentioned that I am using a DSC Pull Server to do the installation. Also, what is the rational fro having all set-target methods use Invoke-Command starting in xSPCreateFarm? Why not make the calls local? Because of the impersonnification?

**Comment by BrianFarnhill** [comment] 2015-07-09 23:57
Yea its because we need to run the calls as a specific domain account that will have access to the databases. In regards to your setup, I think the issue is with your CredSSP configuration. You need to use FQDNs there and each machine needs to have itself listed as a delegate (as that is what we do, we open a 'remote' session to the local host as another user). So where you specify 

    DelegateComputers = "DSCPull"

try changing that to something like 

    DelegateComputers = "SharePoint.mydomain.local"

The reason our examples use a wildcard (such as *.mydomain.local) is so the SharePoint machines can all see each other, but if you want to lock it down specifying the current FQDN of the machine you are on will do. You can test the configuration by doing something like this:

    Enter-PSSession -ComputerName $env:COMPUTERNAME -Credential (Get-Credential) -Authentication CredSSP

This is how we create the sessions, if that works and you get a valid session (using the credentials you have on InstallAccount) then the xSharePoint resources should all behave the same way.

**Comment by NikCharlebois** [comment] 2015-07-10 00:49
Unfortunately, even if I use the FQDN is complains about my session being broken

**Comment by NikCharlebois** [comment] 2015-07-10 18:14
So to add to the confusion, the Error is thrown on the first "Invoke-Command" Line of the xSPCreateFarm resource:

Invoke-Command -Session $session -ArgumentList $PSBoundParameters -ScriptBlock {
        $params = $args[0]
        New-SPConfigurationDatabase -DatabaseName $params.FarmConfigDatabaseName `
                                    -DatabaseServer $params.DatabaseServer `
                                    -Passphrase (ConvertTo-SecureString $params.Passphrase -AsPlainText -force) `
                                    -FarmCredentials $params.FarmAccount `
                                    -SkipRegisterAsDistributedCacheHost:$true `
                                    -AdministrationContentDatabaseName $params.AdminContentDatabaseName
}

But, both the config and the admin database are partially created on the SQL....

**Comment by BrianFarnhill** [comment] 2015-07-11 05:50
OK I now have an environment that is replicating your issue. Leave it with me to troubleshoot on my end as well. I'll let you know how it goes

**Comment by BrianFarnhill** [comment] 2015-07-11 15:05
Nik are you able to let me know a couple of things here?

 - Are you running this with PowerShell 4 or 5?
 - Are you running this one Azure virtual machines (specifically with the DSC VM extension)?

**Comment by NikCharlebois** [comment] 2015-07-13 12:54
Hi Brian,

Thanks for following up. I am using PowerShell 5, April 2015 preview. My VMs are on premises, no DSC VM extension. Thanks

**Comment by BrianFarnhill** [comment] 2015-07-30 23:12
This has been fixed by #60 and been pushed to the dev branch. I have a couple of other changes and fixes I want to roll in before I push it to the master branch and form a release though, so use the dev branch for the time being to resolve this issue.

**Closed by BrianFarnhill** 2015-07-30 23:12 UTC
Labels: bug, question
